# Generated by Django 3.2.5 on 2021-08-01 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.CharField(max_length=200)),
                ('login_url', models.URLField()),
                ('username', models.CharField(max_length=200)),
                ('password', fernet_fields.fields.EncryptedTextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_password_owner', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(blank=True, related_name='personal_password_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Personal Passwords',
                'unique_together': {('site', 'owner')},
            },
        ),
    ]
