# Generated by Django 3.2.5 on 2021-08-01 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_personalpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.CharField(max_length=200)),
                ('login_url', models.URLField()),
                ('username', models.CharField(max_length=200)),
                ('password', fernet_fields.fields.EncryptedTextField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_password_organization', to='user_management.organization')),
            ],
            options={
                'verbose_name_plural': 'Organization Passwords',
            },
        ),
        migrations.CreateModel(
            name='OrganizationPasswordAccessLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.IntegerField(choices=[(1, 'View'), (2, 'Edit')], default=1)),
                ('organization_password', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_password_access_levels', to='user_management.organizationpassword')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_password_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='organizationpassword',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='organization_password_users', through='user_management.OrganizationPasswordAccessLevel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='organizationpassword',
            unique_together={('site', 'organization')},
        ),
    ]
